# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170606_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 7, 17, 53, 245094, tzinfo=utc)),
        ),
    ]
