# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20170606_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveIntegerField()),
                ('brief', models.CharField(max_length=200)),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('doctor', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
