# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20170606_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='inactive_by_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_by_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
